using System;
using System.Diagnostics;
using System.Text;
using System.Web;
using CyberIncidentWPF.Models;

namespace CyberIncidentWPF.Helpers
{
    /// <summary>
    /// Incident bilgileriyle hazır e-posta template'i oluşturur ve varsayılan e-posta istemcisini açar.
    /// </summary>
    public static class EmailHelper
    {
        /// <summary>
        /// Incident bilgileriyle hazır e-posta template'i oluşturur ve varsayılan e-posta istemcisini açar.
        /// </summary>
        public static void SendIncidentEmail(Incident incident, string? recipientEmail = null)
        {
            try
            {
                var subject = $"[{incident.SeverityLevel}] Security Incident #{incident.IncidentId}: {incident.Title}";
                
                var body = new StringBuilder();
                body.AppendLine("Security Incident Report");
                body.AppendLine("========================");
                body.AppendLine();
                body.AppendLine($"Incident ID: {incident.IncidentId}");
                body.AppendLine($"Title: {incident.Title}");
                body.AppendLine($"Type: {incident.IncidentType}");
                body.AppendLine($"Severity: {incident.SeverityLevel}");
                body.AppendLine($"Status: {incident.Status}");
                body.AppendLine($"Incident Date: {incident.IncidentDate:yyyy-MM-dd HH:mm}");
                body.AppendLine();
                body.AppendLine("Description:");
                body.AppendLine(incident.Description);
                body.AppendLine();
                
                if (!string.IsNullOrWhiteSpace(incident.Iocs))
                {
                    body.AppendLine("Indicators of Compromise (IOCs):");
                    body.AppendLine(incident.Iocs);
                    body.AppendLine();
                }
                
                if (!string.IsNullOrWhiteSpace(incident.OpenedByAnalyst))
                {
                    body.AppendLine($"Opened By: {incident.OpenedByAnalyst}");
                }
                
                if (!string.IsNullOrWhiteSpace(incident.ClosedByAnalyst))
                {
                    body.AppendLine($"Closed By: {incident.ClosedByAnalyst}");
                }
                
                body.AppendLine();
                body.AppendLine("---");
                body.AppendLine("This email was generated by Cyber Incident Management System.");

                // mailto: URL'i oluştur
                var mailtoUrl = $"mailto:{recipientEmail ?? ""}?subject={Uri.EscapeDataString(subject)}&body={Uri.EscapeDataString(body.ToString())}";

                // Varsayılan e-posta istemcisini aç
                var psi = new ProcessStartInfo
                {
                    FileName = mailtoUrl,
                    UseShellExecute = true
                };
                Process.Start(psi);
            }
            catch (Exception ex)
            {
                throw new Exception($"Failed to open email client: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// Birden fazla incident için özet e-posta oluşturur.
        /// </summary>
        public static void SendIncidentSummaryEmail(System.Collections.Generic.IEnumerable<Incident> incidents, string? recipientEmail = null)
        {
            try
            {
                var subject = $"Security Incident Summary Report - {DateTime.Now:yyyy-MM-dd}";
                
                var body = new StringBuilder();
                body.AppendLine("Security Incident Summary Report");
                body.AppendLine("================================");
                body.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm}");
                body.AppendLine();

                int count = 0;
                foreach (var incident in incidents)
                {
                    count++;
                    body.AppendLine($"#{incident.IncidentId} [{incident.SeverityLevel}] {incident.Title}");
                    body.AppendLine($"   Type: {incident.IncidentType} | Status: {incident.Status}");
                    body.AppendLine();
                }

                body.AppendLine($"Total Incidents: {count}");
                body.AppendLine();
                body.AppendLine("---");
                body.AppendLine("This email was generated by Cyber Incident Management System.");

                var mailtoUrl = $"mailto:{recipientEmail ?? ""}?subject={Uri.EscapeDataString(subject)}&body={Uri.EscapeDataString(body.ToString())}";

                var psi = new ProcessStartInfo
                {
                    FileName = mailtoUrl,
                    UseShellExecute = true
                };
                Process.Start(psi);
            }
            catch (Exception ex)
            {
                throw new Exception($"Failed to open email client: {ex.Message}", ex);
            }
        }
    }
}
